# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Chambers"
version: "0.1.0-alpha1"
slug: chambers
stage: experimental
description: "Congressional Chamber Status""
url: "https://github.com/chrisgilldc/chambers/"
arch: # Should work on all architectures, it's pure python.
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
services:
  - "mqtt:need"
#map:
#  - share:rw
#options:
#  message: "Hello world..."
#schema:
#  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
